name: CI

on:
  push:
    branches:
      - discord/packager-test-ignore-root-dir

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macOS-latest, ubuntu-latest]
        node-version: [14.x]

    steps:
      - name: Fix git checkout line endings
        run: git config --global core.autocrlf input
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: npm install
      - name: Extra debug in Packager
        run: node add-debug-to-packager
      - name: Test
        run: npm test
        env:
          DEBUG: electron-packager
